project_id = "flyeye"

[api]
enabled = true
port = 55321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55322
shadow_port = 55320
major_version = 17

[studio]
enabled = true
port = 55323

[local_smtp]
enabled = true
port = 55324
smtp_port = 55325
pop3_port = 55326

[analytics]
enabled = false
port = 55327
vector_port = 55328
backend = "postgres"

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["http://127.0.0.1:4173"]
enable_signup = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[edge_runtime]
enabled = true
policy = "per_worker"

[functions.auth-bootstrap]
enabled = true
verify_jwt = true
